### ISSUE TITLE
Let's add an experimental query suite to each language

### ISSUE THREAD

**Issue by aegilops** [advanced-security/codeql-queries#54]
Let's add an experimental query suite to each language.

Sebastian did this for `gh-tailor`:

``` yaml
- description: Java experimental security queries
- queries: .
- include:
    kind:
    - problem
    - path-problem
    - alert
    - path-alert
    tags contain:
    - security
    query path:
      - /experimental\/.*/
- include:
    kind:
    - diagnostic
- include:
    kind:
    - metric
    tags contain:
    - summary
- exclude:
    deprecated: //
- exclude:
    query path:
      - Metrics/Summaries/FrameworkCoverage.ql
      - /Diagnostics/Internal/.*/
- exclude:
    tags contain:
      - model-generator
```
